-- liquibase formatted sql

-- changeset orhangazibarak:1760607544531-9 splitStatements:false
CREATE TABLE claps (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_id VARCHAR(255) NOT NULL, clap_count INTEGER NOT NULL, user_public_id UUID NOT NULL);

-- changeset orhangazibarak:1760607544531-10 splitStatements:false
ALTER TABLE claps ADD CONSTRAINT who_clapped_article UNIQUE (user_public_id, article_id);

-- changeset orhangazibarak:1760607544531-1 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE favorites DROP CONSTRAINT unique_article_favorite;

-- changeset orhangazibarak:1760607544531-2 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE favorites ADD CONSTRAINT unique_article_favorite UNIQUE (user_public_id, article_id);

-- changeset orhangazibarak:1760607544531-3 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE follows DROP CONSTRAINT unique_user_follow;

-- changeset orhangazibarak:1760607544531-4 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE follows ADD CONSTRAINT unique_user_follow UNIQUE (user_public_id, followed_user_public_id);

-- changeset orhangazibarak:1760607544531-5 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

-- changeset orhangazibarak:1760607544531-6 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset orhangazibarak:1760607544531-7 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users DROP CONSTRAINT UC_USERSPUBLIC_ID_COL;

-- changeset orhangazibarak:1760607544531-8 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users ADD CONSTRAINT UC_USERSPUBLIC_ID_COL UNIQUE (public_id);

