-- liquibase formatted sql

-- changeset orhangazibarak:1760352640233-9 splitStatements:false
CREATE TABLE follows (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, followed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, followed_user_public_id UUID NOT NULL, user_public_id UUID NOT NULL, CONSTRAINT "followsPK" PRIMARY KEY (id));

-- changeset orhangazibarak:1760352640233-10 splitStatements:false
ALTER TABLE follows ADD CONSTRAINT unique_user_follow UNIQUE (user_public_id, followed_user_public_id);

-- changeset orhangazibarak:1760352640233-1 splitStatements:false
DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'article' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table public.article drop constraint "' || constraint_name || '"';
END $$;

-- changeset orhangazibarak:1760352640233-2 splitStatements:false
ALTER TABLE article ADD CONSTRAINT "articlePK" PRIMARY KEY (id);

-- changeset orhangazibarak:1760352640233-3 splitStatements:false
DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'users' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table public.users drop constraint "' || constraint_name || '"';
END $$;

-- changeset orhangazibarak:1760352640233-4 splitStatements:false
ALTER TABLE users ADD CONSTRAINT "usersPK" PRIMARY KEY (id);

-- changeset orhangazibarak:1760352640233-5 splitStatements:false
ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

-- changeset orhangazibarak:1760352640233-6 splitStatements:false
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset orhangazibarak:1760352640233-7 splitStatements:false
ALTER TABLE users DROP CONSTRAINT UC_USERSPUBLIC_ID_COL;

-- changeset orhangazibarak:1760352640233-8 splitStatements:false
ALTER TABLE users ADD CONSTRAINT UC_USERSPUBLIC_ID_COL UNIQUE (public_id);

