-- liquibase formatted sql

-- changeset orhangazibarak:1759062012381-1 splitStatements:false
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE, email VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE, username VARCHAR(255) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset orhangazibarak:1759062012381-2 splitStatements:false
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

