-- liquibase formatted sql

-- changeset orhangazibarak:1760523833840-7 splitStatements:false
CREATE TABLE favorites (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_id VARCHAR(255) NOT NULL, favorite_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, user_public_id UUID NOT NULL);

-- changeset orhangazibarak:1760523833840-8 splitStatements:false
ALTER TABLE favorites ADD CONSTRAINT unique_article_favorite UNIQUE (user_public_id, article_id);

-- changeset orhangazibarak:1760523833840-1 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE follows DROP CONSTRAINT unique_user_follow;

-- changeset orhangazibarak:1760523833840-2 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE follows ADD CONSTRAINT unique_user_follow UNIQUE (user_public_id, followed_user_public_id);

-- changeset orhangazibarak:1760523833840-3 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users DROP CONSTRAINT UC_USERSPUBLIC_ID_COL;

-- changeset orhangazibarak:1760523833840-4 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users ADD CONSTRAINT UC_USERSPUBLIC_ID_COL UNIQUE (public_id);

-- changeset orhangazibarak:1760523833840-5 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

-- changeset orhangazibarak:1760523833840-6 splitStatements:false
-- validCheckSum: ANY
-- ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

